name              "libqt4"
maintainer        "Jordan Yaker"
license           "MIT"
description       "Install libqt4 packages"
version           "0.2.0"
depends           "cmake"
supports          "ubuntu"

recipe            "libqt4", "Install a relatively complete of libqt4 packages"
recipe            "libqt4::base",    "Install base support for libqt4 packages"
recipe            "libqt4::core",    "Install the core set of libqt4 packages"
recipe            "libqt4::dbus",    "Install dbus support for libqt4 packages"
recipe            "libqt4::dev",     "Install development support for libqt4 packages"
recipe            "libqt4::full",    "Install every libqt4 package available"
recipe            "libqt4::network", "Install network support for libqt4 packages"
recipe            "libqt4::ruby",    "Install ruby support for libqt4 packages"
recipe            "libqt4::webkit",  "Install webkit support for libqt4 packages"
recipe            "libqt4::xml",     "Install xml support for libqt4 packages"